### ISSUE TITLE
push data sequence to short

### ISSUE THREAD

**Issue by aisvn-data** [aisvn-data/solarpower#10]
## Sequence length

If you look at line 27 you see that

```
uint64_t TIME_TO_SLEEP = 60;
```

That is just one minute, not every two minutes (or 120 seconds). This needs to be fixed!

**Comment by kreier** [comment]
Will be fixed in release 0.7

**Comment by aisvn-data** [comment]
release 0,7 implemented

**Comment by aisvn-data** [comment]
version 0.7 published, problem solved.
