### ISSUE TITLE
old software version provided

### ISSUE THREAD

**Issue by aisvn-data** [aisvn-data/solarpower#12]
Please update the released software.

**Comment by kreier** [comment]
On [github.com/kreier/solarmeter](https://github.com/kreier/solarmeter) we have already 0.8

**Comment by ssis-robotics** [comment]
It seems not a lot changed in version 0.8 on [github.com/kreier/solarmeter](https://github.com/kreier/solarmeter). Is that documented?

**Comment by ssis-robotics** [comment]
Version 0.8 is actually released here: [https://github.com/aisvn-data/solarpower/releases](https://github.com/aisvn-data/solarpower/releases). I think this could be closed.

**Comment by aisvn-data** [comment]
OK, it í finished then.
