### ISSUE TITLE
Please relocate the calculation of the battery voltage value to a different location.

### ISSUE THREAD

**Issue by kreier** [aisvn-data/solarpower#7]
Please relocate the calculation of the battery voltage value to a different location.

_Originally posted by @kreier in https://github.com/aisvn-data/solarpower/pull/3#discussion_r528534448_

**Comment by kreier** [comment]
In the constructor of the JSON object there should not be the very definition and mathematical calculation of the determined voltage.

**Comment by aisvn-data** [comment]
It is changed with v0.5

**Comment by kreier** [comment]
Checked your merge, fixed with v0.5 - thanks!
